# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 800db8ee166fdd27980794dc7fb4dca5a5ce50b21791aead3b5be49f4b348dc6a774362a14f9f71f95222c69696d5dfdce48f2586a10aa5bcd8f87d41beaa901

test:
  secret_key_base: 24216fb7d6ab9fdb52b479c2b0f2736c7c17cb35b9dc52663aaa69b779d790a5b57a4e54f83d67d576f2c06c3b1aa2c0cd105c643c7c51d1ce6c4e0c3c95f3ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
